# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TmpcmpUKibsgYpdeRxCzlw0JKhP8ZtZ9
"""

import tkinter as tk
import random

# List of Thai consonants with their names
thai_consonants = [
    ("ก", "กอ ไก่ (gor kai)"),
    ("ข", "ขอ ไข่ (khor khai)"),
    ("ค", "คอ ควาย (khor khwai)"),
    ("ง", "งอ งู (ngor ngu)"),
    ("จ", "จอ จาน (jor jaan)"),
    ("ฉ", "ฉอ ฉิ่ง (chor ching)"),
    ("ช", "ชอ ช้าง (chor chaang)"),
    ("ซ", "ซอ โซ่ (sor so)"),
    ("ญ", "ญอ หญิง (yor ying)"),
    ("ฎ", "ฎอ ชฎา (dor cha-daa)"),
    ("ฐ", "ฐอ ฐาน (thor thaan)"),
    ("ณ", "ณอ เณร (nor nen)"),
    ("ด", "ดอ เด็ก (dor dek)"),
    ("ต", "ตอ เต่า (tor tao)"),
    ("ถ", "ถอ ถุง (thor thung)"),
    ("ท", "ทอ ทหาร (thor thahaan)"),
    ("น", "นอ หนู (nor nu)"),
    ("บ", "บอ ใบไม้ (bor bai-mai)"),
    ("ป", "ปอ ปลา (por plaa)"),
    ("ผ", "ผอ ผึ้ง (phor phueng)"),
    ("ฝ", "ฝอ ฝา (for faa)"),
    ("พ", "พอ พาน (phor phaan)"),
    ("ฟ", "ฟอ ฟัน (for fan)"),
    ("ม", "มอ ม้า (mor maa)"),
    ("ย", "ยอ ยักษ์ (yor yak)"),
    ("ร", "รอ เรือ (ror ruea)"),
    ("ล", "ลอ ลิง (lor ling)"),
    ("ว", "วอ แหวน (wor waen)"),
    ("ศ", "ศอ ศาลา (sor saa-laa)"),
    ("ส", "สอ เสือ (sor sua)"),
    ("ห", "หอ หีบ (hor heep)"),
]

class FlashcardApp:
    def __init__(self, root):
        self.root = root
        self.root.title("Thai Consonant Flashcards")

        self.card_frame = tk.Frame(root, bg="white", width=300, height=200, relief="ridge", bd=3)
        self.card_frame.pack(pady=20)

        self.card_label = tk.Label(self.card_frame, text="", font=("Arial", 50), bg="white")
        self.card_label.pack(expand=True)

        self.flip_button = tk.Button(root, text="Flip", command=self.flip_card, font=("Arial", 14))
        self.flip_button.pack(pady=5)

        self.next_button = tk.Button(root, text="Next", command=self.next_card, font=("Arial", 14))
        self.next_button.pack(pady=5)

        self.current_card = None
        self.is_flipped = False

        self.next_card()  # Load first card

    def next_card(self):
        self.current_card = random.choice(thai_consonants)
        self.card_label.config(text=self.current_card[0])  # Show only the Thai consonant
        self.is_flipped = False

    def flip_card(self):
        if not self.is_flipped:
            self.card_label.config(text=f"{self.current_card[0]} -> {self.current_card[1]}")
            self.is_flipped = True

if __name__ == "__main__":
    root = tk.Tk()
    app = FlashcardApp(root)
    root.mainloop()